title: Leo Sun
tagline: MIT Class of 2028
description: Robotics, autonomy, and AI projects by Leo Sun.
url: "https://www.leosun.org"
baseurl: ""
lang: en
timezone: America/Los_Angeles

author:
  name: Leo Sun
  email: leosun@mit.edu

github:
  username: lleosunn

linkedin:
  username: lleosunn

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /projects/:slug/
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - tools
  - "*.gem"
  - "*.gemspec"
